# Python 3.10을 사용하는 기본 이미지
FROM python:3.10-slim

# 작업 디렉토리 설정
WORKDIR /app

# 필요한 Python 패키지 목록을 requirements.txt 파일에 저장
COPY requirements.txt .

# 필요한 패키지 설치
RUN pip install --no-cache-dir -r requirements.txt

# 현재 디렉토리의 모든 파일을 컨테이너의 작업 디렉토리로 복사
COPY . .

# 환경 변수 설정 (예시)
# 이 부분은 실제 환경에 맞게 수정할 필요가 있습니다.
ENV TOKEN=your_token
ENV OWNER=your_owner
ENV REPO_NAME=your_repo_name
ENV NOTION_TOKEN=your_notion_token
ENV NOTION_DB=your_database_id

# 컨테이너가 실행될 때 실행할 명령
CMD ["python", "./main.py"]